veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % ls
db.sqlite3                      dojo_ninjas_shell_app           dojo_ninjas_shell_project       manage.py
veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % cd ..
veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell % cd ..
veriesmacbookpro@Veriess-MacBook-Pro django_intro % cd ..
veriesmacbookpro@Veriess-MacBook-Pro django % ls
django_extras           django_full_stack       django_fundamentals     django_intro            django_orm
veriesmacbookpro@Veriess-MacBook-Pro django % cd ..
veriesmacbookpro@Veriess-MacBook-Pro python_stack % ls
_python         django          django-admin    flask           my_environments mysql
veriesmacbookpro@Veriess-MacBook-Pro python_stack % cd my_environments 
veriesmacbookpro@Veriess-MacBook-Pro my_environments % source djangoPy3Env/bin/activate
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro my_environments % cd ..
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro python_stack % cd django
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro django % cd django_intro        
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro django_intro % ls
dojo_ninjas_shell               first_django_project            ninja_gold                      time_project
dojo_survey                     first_django_project.zip        ninja_gold.zip                  time_project.zip
dojo_survey.zip                 first_project                   random_word_generator           users_shell
dojo_survey_revisited           get_vs_post                     random_word_generator.zip
dojo_survey_revisited.zip       named_routes                    redirect_project
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro django_intro % cd dojo_ninjas_shell 
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell % ls
dojo_ninjas_shell_project
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell % cd dojo_ninjas_shell_project 
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % ls
db.sqlite3                      dojo_ninjas_shell_app           dojo_ninjas_shell_project       manage.py
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Traceback (most recent call last):
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/manage.py", line 21, in <module>
    main()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 579, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 564, in start_django
    reloader.run(django_main_thread)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 272, in run
    get_resolver().urlconf_module
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/urls/resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/dojo_ninjas_shell_project/urls.py", line 4, in <module>
    path('', include('dojo_ninjas_shell_app.urls')),
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    self._target(*self._args, **self._kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 54, in wrapper
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    fn(*args, **kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
    self.check(display_num_errors=True)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 387, in check
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/dojo_ninjas_shell_app/urls.py", line 4, in <module>
    all_issues = self._run_checks(
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 377, in _run_checks
    urlpatterns [
    return checks.run_checks(**kwargs)
NameError: name 'urlpatterns' is not defined
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/checks/registry.py", line 72, in run_checks
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Traceback (most recent call last):
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/manage.py", line 21, in <module>
    main()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 579, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 564, in start_django
    reloader.run(django_main_thread)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 272, in run
    get_resolver().urlconf_module
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/urls/resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/dojo_ninjas_shell_project/urls.py", line 4, in <module>
    path('', include('dojo_ninjas_shell_app.urls')),
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/dojo_ninjas_shell_app/urls.py", line 4, in <module>
    urlpatterns [
NameError: name 'urlpatterns' is not defined
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Traceback (most recent call last):
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/manage.py", line 21, in <module>
    main()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 579, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 564, in start_django
    reloader.run(django_main_thread)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 272, in run
    get_resolver().urlconf_module
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/urls/resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    self._target(*self._args, **self._kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 54, in wrapper
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    fn(*args, **kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    self.check(display_num_errors=True)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 387, in check
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    all_issues = self._run_checks(
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/base.py", line 377, in _run_checks
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
    return checks.run_checks(**kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/checks/registry.py", line 72, in run_checks
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    new_errors = check(app_configs=app_configs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/dojo_ninjas_shell_project/urls.py", line 3, in <module>
    all_namespaces = _load_all_namespaces(resolver)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    urlpatterns [
NameError: name 'urlpatterns' is not defined
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

April 05, 2021 - 19:12:11
Django version 2.2, using settings 'dojo_ninjas_shell_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/dojo_ninjas_shell_app/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

April 05, 2021 - 20:55:26
Django version 2.2, using settings 'dojo_ninjas_shell_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/dojo_ninjas_shell_app/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

April 05, 2021 - 20:58:14
Django version 2.2, using settings 'dojo_ninjas_shell_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/dojo_ninjas_shell_app/models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[0](_exception[1]).with_traceback(_exception[2])
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
SyntaxError: invalid syntax (models.py, line 22)
^C%                                                                                                                                                                                                                                                                            
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % ls
db.sqlite3                      dojo_ninjas_shell_app           dojo_ninjas_shell_project       manage.py
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py makemigrations
Traceback (most recent call last):
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/manage.py", line 21, in <module>
    main()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/my_environments/djangoPy3Env/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Volumes/CODINGDRV/CodingDojo/Python_New/python_stack/django/django_intro/dojo_ninjas_shell/dojo_ninjas_shell_project/dojo_ninjas_shell_app/models.py", line 22
    on_delete=models.CASCADE,
    ^
SyntaxError: invalid syntax
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py runserver     
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

April 05, 2021 - 21:29:50
Django version 2.2, using settings 'dojo_ninjas_shell_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C%                                                                                                                                                                                                                                                                            
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py makemigrations
Migrations for 'dojo_ninjas_shell_app':
  dojo_ninjas_shell_app/migrations/0001_initial.py
    - Create model Dojo
    - Create model Ninja
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py migrate       
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dojo_ninjas_shell_app, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying dojo_ninjas_shell_app.0001_initial... OK
  Applying sessions.0001_initial... OK
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py shell
Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from dojo_ninjas_shell_app.models import Dojo, Ninja
>>> dojo1 = Dojo.objects.create(name ="Dojo 1", city = "Chicago", state = "IL")
>>> Dojo1
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo1' is not defined
>>> dojo1
<Dojo: Dojo 1>
>>> dojo2 = Dojo.objects.create(name ="Dojo 2", city = "Brookhaven", state = "MS")
>>> dojo2
<Dojo: Dojo 2>
>>> dojo3 = Dojo.objects.create(name ="Dojo 3", city = "Montgomery", state = "AL")
>>> dojo3
<Dojo: Dojo 3>
>>> Dojo.objects.all()
<QuerySet [<Dojo: Dojo 1>, <Dojo: Dojo 2>, <Dojo: Dojo 3>]>
>>> dojo1.delete()
(1, {'dojo_ninjas_shell_app.Ninja': 0, 'dojo_ninjas_shell_app.Dojo': 1})
>>> dojo2.delete()
(1, {'dojo_ninjas_shell_app.Ninja': 0, 'dojo_ninjas_shell_app.Dojo': 1})
>>> dojo3.delete()
(1, {'dojo_ninjas_shell_app.Ninja': 0, 'dojo_ninjas_shell_app.Dojo': 1})
>>> dojo1 = Dojo.objects.create(name ="Dojo 1", city = "New York", state = "New York")
>>> dojo1.delete()
(1, {'dojo_ninjas_shell_app.Ninja': 0, 'dojo_ninjas_shell_app.Dojo': 1})
>>> dojo1 = Dojo.objects.create(name ="Dojo 1", city = "New York", state = "NY")
>>> dojo2 = Dojo.objects.create(name ="Dojo 2", city = "Compton", state = "CA")
>>> dojo3 = Dojo.objects.create(name ="Dojo 3", city = "New Orleans", state = "LA")
>>> ninja1 = Ninja.objects.create(first_name = "Veries", last_name = "Seals", dojo1)
  File "<console>", line 1
    ninja1 = Ninja.objects.create(first_name = "Veries", last_name = "Seals", dojo1)
                                                                                   ^
SyntaxError: positional argument follows keyword argument
>>> ninja1 = Ninja.objects.create(first_name = "Veries", last_name = "Seals", dojo = dojo1)
>>> ninja2 = Ninja.objects.create(first_name = "Demarcus", last_name = "Seals", dojo = dojo1)
>>> ninja3 = Ninja.objects.create(first_name = "ANya", last_name = "Seals", dojo = dojo1)
>>> ninja4 = Ninja.objects.create(first_name = "Aleceia", last_name = "Seals", dojo = dojo2)
>>> ninja5 = Ninja.objects.create(first_name = "Jerralyn", last_name = "Seals", dojo = dojo2)
>>> ninja6 = Ninja.objects.create(first_name = "TYaanah", last_name = "Brumfield", dojo = dojo2)
>>> ninja7 = Ninja.objects.create(first_name = "Kingston", last_name = "Jones", dojo = dojo3)
>>> ninja8 = Ninja.objects.create(first_name = "Constance", last_name = "Washington", dojo = dojo3)
>>> ninja9 = Ninja.objects.create(first_name = "Veries", last_name = "Seals IV", dojo = dojo3)
>>> Ninja.objects.dojo1
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Manager' object has no attribute 'dojo1'
>>> Dojo.objects.first().ninjas.all()
<QuerySet [<Ninja: Veries Seals>, <Ninja: Demarcus Seals>, <Ninja: ANya Seals>]>
>>> Dojo.objects.first().ninjas.last()
<Ninja: ANya Seals>
>>> Dojo.objects.last().ninjas.all()
<QuerySet [<Ninja: Kingston Jones>, <Ninja: Constance Washington>, <Ninja: Veries Seals IV>]>
>>> Ninja.objects.last().dojo
<Dojo: Dojo 3>
>>> 
KeyboardInterrupt
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py makemigrations
You are trying to add a non-nullable field 'description' to dojo without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 2
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py makemigrations
You are trying to add a non-nullable field 'description' to dojo without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 2
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py makemigrations
Migrations for 'dojo_ninjas_shell_app':
  dojo_ninjas_shell_app/migrations/0002_dojo_description.py
    - Add field description to dojo
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py migrate       
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dojo_ninjas_shell_app, sessions
Running migrations:
  Applying dojo_ninjas_shell_app.0002_dojo_description... OK
(djangoPy3Env) veriesmacbookpro@Veriess-MacBook-Pro dojo_ninjas_shell_project % python manage.py shell
Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> dojo4 = Dojo.objects.create(name ="Dojo 4", city = "McComb", state = "MS")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> dojo4 = Dojo.objects.create(name ="Dojo 4", city = "McComb", state = "MS")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> from dojo_ninjas_shell_app.models import Dojo, Ninja
>>> dojo4 = Dojo.objects.create(name ="Dojo 4", city = "McComb", state = "MS")
>>> dojo4
<Dojo: Dojo 4>
>>> 